version: '3'
services:
  backend:
    # build:
    #   dockerfile: dockerfile
    image: ghcr.io/sysumatrixdl/backend:master
    container_name: matrixdl-backend
    environment:
      - "BACKEND_HOST=localhost"  # for local dev
    ports:
      - "8000:8000"
    networks:
      - og-network
    depends_on:
      - open-gauss

  open-gauss:
    image: ghcr.io/sysumatrixdl/opengauss:latest
    container_name: matrixdl-opengauss
    ports:
      - "5432:5432"
    volumes:
      - ./sql/open-gauss/data:/opt/openGauss/data
    networks:
      - og-network

  grafana:
    image: ghcr.io/sysumatrixdl/grafana:latest
    # build:
    #   context: ./grafana/docker
    #   dockerfile: dockerfile
    container_name: matridl-grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    depends_on:
      - open-gauss
    networks:
      - og-network
    links:
      - open-gauss

networks:
  og-network:
    driver: bridge
    ipam:
      # 避免和校园网网段(172.12.0.0/16)冲突
      driver: default
      config:
        - subnet: 192.168.114.0/24
          gateway: 192.168.114.254